use anyhow::{Context, Result};
use async_trait::async_trait;
use percent_encoding::{AsciiSet, CONTROLS, utf8_percent_encode};
use std::collections::HashSet;

use super::backend::{MemoryBackend, NoteInput};
use super::memory::{MemoryEdge, Note};
use crate::embeddings::blob_to_vec;

mod sync;
mod wire_types;
pub use sync::{BatchItemResult, BatchPushItem, BatchPushResult, CloudSyncClient, RemoteEntry};
pub use wire_types::ConflictInfo;
use wire_types::*;

/// Characters that must be percent-encoded inside a single URL **path segment**.
///
/// `derive_project_id` produces slugs that contain `/` (`local/<blake3-hex>`,
/// `github.com/owner/repo`). Inserted raw into `/v1/projects/{project_id}/…`
/// the slashes split the segment and break axum routing (→ 404). We percent-encode
/// the slug so the whole slug occupies exactly one captured `{project_id}` segment;
/// axum percent-decodes it back to the original slug server-side, so the
/// persistence key (`projects.slug`, UNIQUE) is unchanged. See spelunk decision #106.
///
/// Mirrors `PROJECT_ID_SEGMENT` / `encode_project_id` in
/// `spelunk-cli/src/server_client.rs` — duplicated here because spelunk-core
/// cannot depend on spelunk-cli.
const PROJECT_ID_SEGMENT: &AsciiSet = &CONTROLS
    .add(b' ')
    .add(b'"')
    .add(b'#')
    .add(b'<')
    .add(b'>')
    .add(b'?')
    .add(b'`')
    .add(b'{')
    .add(b'}')
    .add(b'/')
    .add(b'%');

/// Percent-encode a `project_id` slug for safe use as a single URL path segment.
///
/// Only the segment is encoded (not the surrounding URL); `/` → `%2F` etc.
pub(super) fn encode_project_id(project_id: &str) -> String {
    utf8_percent_encode(project_id, PROJECT_ID_SEGMENT).to_string()
}

// ── Cloud-api slug → UUID resolution (ADR-005) ────────────────────────────────

/// Name of the cache file (inside the `.spelunk/` directory) that stores the
/// last resolved slug → UUID mapping for cloud-api routing.
const CLOUD_PROJECT_CACHE_FILE: &str = "cloud-project-id.lock";

/// On-disk shape of `.spelunk/cloud-project-id.lock`.
///
/// The slug is stored alongside the UUID so a `project_id` change (slug rename
/// or a different project) invalidates the cache automatically: on read, if the
/// stored `slug` does not match the current `project_id`, the cache is
/// discarded and the UUID re-resolved (ADR-005 D4).
#[derive(serde::Serialize, serde::Deserialize)]
struct CloudProjectCache {
    slug: String,
    uuid: uuid::Uuid,
}

/// Returns `true` when `SPELUNK_NO_SLUG_CACHE` is set to a truthy value.
///
/// Forces a fresh `GET /v1/projects` lookup, bypassing (and overwriting) the
/// `.spelunk/cloud-project-id.lock` cache. Useful for tests and for recovering
/// from a stale lock after a slug rename (ADR-005 D4).
fn no_slug_cache_env_set() -> bool {
    matches!(
        std::env::var("SPELUNK_NO_SLUG_CACHE").as_deref(),
        Ok("1") | Ok("true") | Ok("yes")
    )
}

/// Read the cached UUID for `slug` from `<spelunk_dir>/cloud-project-id.lock`.
///
/// Returns `None` when the file is missing, unparseable, or its stored slug
/// does not match `slug` (stale cache → re-resolve). A corrupt cache is never
/// fatal: it is treated as a miss.
fn read_cloud_project_cache(spelunk_dir: &std::path::Path, slug: &str) -> Option<uuid::Uuid> {
    let path = spelunk_dir.join(CLOUD_PROJECT_CACHE_FILE);
    let raw = std::fs::read_to_string(&path).ok()?;
    let cached: CloudProjectCache = toml::from_str(&raw).ok()?;
    if cached.slug == slug {
        Some(cached.uuid)
    } else {
        None
    }
}

/// Persist the resolved `slug` → `uuid` mapping to
/// `<spelunk_dir>/cloud-project-id.lock`.
///
/// Best-effort: a write failure is logged but not fatal — the resolution still
/// succeeds, the next invocation just re-resolves.
fn write_cloud_project_cache(spelunk_dir: &std::path::Path, slug: &str, uuid: uuid::Uuid) {
    let cache = CloudProjectCache {
        slug: slug.to_string(),
        uuid,
    };
    let body = match toml::to_string(&cache) {
        Ok(b) => b,
        Err(e) => {
            tracing::warn!("could not serialize cloud-project-id cache: {e}");
            return;
        }
    };
    let contents = format!(
        "# Auto-generated by spelunk. Do not edit. Safe to delete — will be regenerated.\n{body}"
    );
    let path = spelunk_dir.join(CLOUD_PROJECT_CACHE_FILE);
    if let Err(e) = std::fs::write(&path, contents) {
        tracing::warn!(
            "could not write cloud-project-id cache at {}: {e}",
            path.display()
        );
    }
}

/// Resolve a human project slug to the cloud-api UUID (ADR-005).
///
/// - If `project_id` already parses as a UUID, it is returned unchanged — no
///   lookup, no cache write (ADR-005 D5).
/// - If `server_url` is unset or loopback, no resolution is attempted: the
///   loopback OSS spelunk-server accepts arbitrary slugs as the project key, so
///   no UUID lookup is needed — the caller keeps using the slug directly.
///   Callers must guard with [`crate::config::is_loopback_url`] before calling
///   (see D6); to make a mis-wired caller easy to diagnose, an unset/loopback
///   `server_url` with a non-UUID slug returns a clear error here.
/// - Otherwise the slug is resolved by calling `GET {server_url}/v1/projects`
///   (Bearer `server_key`), matching on `slug == project_id`, and the result is
///   cached to `<spelunk_dir>/cloud-project-id.lock`.
///
/// `SPELUNK_NO_SLUG_CACHE=1` forces a fresh lookup that bypasses the cache.
pub async fn resolve_cloud_project_uuid(
    project_id: &str,
    server_url: &str,
    server_key: Option<&str>,
    spelunk_dir: &std::path::Path,
) -> Result<uuid::Uuid> {
    // D5: raw UUID in config → use directly, no lookup, no cache.
    if let Ok(uuid) = uuid::Uuid::parse_str(project_id) {
        return Ok(uuid);
    }

    // D6: loopback / unset server_url is the OSS-server path, which accepts the
    // slug directly. Resolution should not have been attempted; bail clearly so
    // a mis-wired caller is easy to diagnose rather than silently issuing a
    // cloud-api call against a loopback server.
    if server_url.trim().is_empty() || crate::config::is_loopback_url(server_url) {
        anyhow::bail!(
            "slug→UUID resolution is only for non-loopback cloud-api servers; \
             got server_url = {server_url:?}. This is a bug: callers must skip \
             resolution for loopback/unset URLs and use the slug directly."
        );
    }

    resolve_cloud_project_uuid_inner(project_id, server_url, server_key, spelunk_dir).await
}

/// The cache + `GET /v1/projects` half of [`resolve_cloud_project_uuid`],
/// without the raw-UUID short-circuit or the loopback guard.
///
/// Split out so unit tests can exercise the resolution/caching behaviour
/// against a loopback mock server (which the public function's loopback guard
/// would otherwise reject). Production callers always go through
/// [`resolve_cloud_project_uuid`].
async fn resolve_cloud_project_uuid_inner(
    project_id: &str,
    server_url: &str,
    server_key: Option<&str>,
    spelunk_dir: &std::path::Path,
) -> Result<uuid::Uuid> {
    let use_cache = !no_slug_cache_env_set();

    // D4: cache hit (and slug matches) → return immediately.
    if use_cache && let Some(uuid) = read_cloud_project_cache(spelunk_dir, project_id) {
        return Ok(uuid);
    }

    let url = format!("{}/v1/projects", server_url.trim_end_matches('/'));
    let client = reqwest::Client::new();
    let mut req = client.get(&url);
    if let Some(key) = server_key {
        req = req.header("Authorization", format!("Bearer {key}"));
    }

    let resp = req
        .send()
        .await
        .with_context(|| format!("GET {url} (resolving project slug {project_id:?})"))?
        .error_for_status()
        .with_context(|| {
            format!("server returned error for GET {url} while resolving slug {project_id:?}")
        })?
        .json::<CloudProjectListResponse>()
        .await
        .context("parsing GET /v1/projects response")?;

    let mut matches = resp
        .projects
        .into_iter()
        .filter(|p| p.slug.as_deref() == Some(project_id));

    let first = matches.next().ok_or_else(|| {
        anyhow::anyhow!(
            "project slug {project_id:?} not found on {server_url}.\n       \
             Run 'spelunk projects list' or check .spelunk/config.toml."
        )
    })?;

    // D2: slug is UNIQUE server-side; multiple matches should be impossible.
    // Defensive: use the first and warn rather than failing.
    if matches.next().is_some() {
        tracing::warn!(
            "multiple projects matched slug {project_id:?} on {server_url}; using the first"
        );
    }

    if use_cache {
        write_cloud_project_cache(spelunk_dir, project_id, first.id);
    }

    Ok(first.id)
}

/// HTTP client for the spelunk-server REST API.
///
/// All routes are scoped under `/v1/projects/{project_id}/`.
pub struct RemoteMemoryBackend {
    pub client: reqwest::Client,
    pub base_url: String,
    pub project_id: String,
    pub api_key: Option<String>,
}

impl RemoteMemoryBackend {
    fn url(&self, path: &str) -> String {
        // Percent-encode the project_id path segment: slugs contain `/`
        // (`local/<hex>`, `github.com/owner/repo`) which would otherwise split
        // the segment and break axum routing → 404. See spelunk decision #106.
        format!(
            "{}/v1/projects/{}/{}",
            self.base_url.trim_end_matches('/'),
            encode_project_id(&self.project_id),
            path
        )
    }

    fn authed(&self, req: reqwest::RequestBuilder) -> reqwest::RequestBuilder {
        if let Some(key) = &self.api_key {
            req.header("Authorization", format!("Bearer {key}"))
        } else {
            req
        }
    }
}

// ── Trait implementation ──────────────────────────────────────────────────────

#[async_trait]
impl MemoryBackend for RemoteMemoryBackend {
    async fn add(&self, input: NoteInput) -> Result<i64> {
        let embedding = input.embedding.as_deref().map(blob_to_vec);
        let body = AddNoteRequest {
            kind: input.kind,
            title: input.title,
            body: input.body,
            tags: input.tags,
            linked_files: input.linked_files,
            embedding,
            source_ref: input.source_ref,
            valid_at: input.valid_at,
        };
        let http_resp = self
            .authed(self.client.post(self.url("memory")))
            .json(&body)
            .send()
            .await
            .context("POST /memory")?;

        let status = http_resp.status();

        // 409 means "stored but conflicting" — treat as success but emit a warning.
        if status == reqwest::StatusCode::CONFLICT {
            let resp = http_resp
                .json::<AddNoteResponse>()
                .await
                .context("parsing POST /memory 409 response")?;
            if !resp.conflicts.is_empty() {
                eprintln!("warning: memory entry conflicts with existing entries:");
                for c in &resp.conflicts {
                    eprintln!(
                        "  · #{} \"{}\" (similarity: {:.2})",
                        c.id, c.title, c.similarity
                    );
                }
            }
            return Ok(resp.id);
        }

        let resp = http_resp
            .error_for_status()
            .context("server returned error for POST /memory")?
            .json::<AddNoteResponse>()
            .await
            .context("parsing POST /memory response")?;
        Ok(resp.id)
    }

    /// Remote backend: timeline search falls back to regular semantic search.
    async fn search_timeline(
        &self,
        query_blob: &[u8],
        query: &str,
        limit: usize,
    ) -> Result<Vec<Note>> {
        self.search(query_blob, query, limit, None).await
    }

    /// The server has no native embedder client-side hook — it embeds `query`
    /// server-side (see `spelunk-server::handlers::search_notes`). The
    /// pre-computed `query_blob` is what local backends use for KNN; the
    /// remote backend ignores it and sends the raw query text instead, or the
    /// server's required `query: String` field is missing and axum rejects
    /// the request with 422 before the handler ever runs (spelunk#359).
    async fn search(
        &self,
        _query_blob: &[u8],
        query: &str,
        limit: usize,
        _as_of: Option<i64>,
    ) -> Result<Vec<Note>> {
        let body = SearchRequest {
            query: query.to_string(),
            limit,
        };
        let resp = self
            .authed(self.client.post(self.url("memory/search")))
            .json(&body)
            .send()
            .await
            .context("POST /memory/search")?
            .error_for_status()
            .context("server returned error for POST /memory/search")?
            .json::<Vec<NoteResponse>>()
            .await
            .context("parsing search response")?;
        Ok(resp.into_iter().map(Into::into).collect())
    }

    /// Remote backend: BM25 text search is not supported — falls back to semantic search.
    async fn search_text(
        &self,
        _query: &str,
        _limit: usize,
        _as_of: Option<i64>,
    ) -> Result<Vec<Note>> {
        anyhow::bail!(
            "BM25 text search is not supported by the remote memory backend. \
             Use --mode semantic or omit --mode to use the default hybrid mode."
        )
    }

    /// Remote backend: hybrid search falls back to semantic search
    /// (server-side FTS is not available in this client).
    async fn search_hybrid(
        &self,
        query_blob: &[u8],
        query: &str,
        limit: usize,
        as_of: Option<i64>,
    ) -> Result<Vec<Note>> {
        self.search(query_blob, query, limit, as_of).await
    }

    async fn list(
        &self,
        kind_filter: Option<&str>,
        limit: usize,
        include_archived: bool,
        as_of: Option<i64>,
    ) -> Result<Vec<Note>> {
        let mut req = self.client.get(self.url("memory")).query(&[
            ("limit", limit.to_string().as_str()),
            ("archived", if include_archived { "true" } else { "false" }),
        ]);
        if let Some(kind) = kind_filter {
            req = req.query(&[("kind", kind)]);
        }
        if let Some(ts) = as_of {
            req = req.query(&[("as_of", ts.to_string().as_str())]);
        }
        let resp = self
            .authed(req)
            .send()
            .await
            .context("GET /memory")?
            .error_for_status()
            .context("server returned error for GET /memory")?
            .json::<Vec<NoteResponse>>()
            .await
            .context("parsing list response")?;
        Ok(resp.into_iter().map(Into::into).collect())
    }

    async fn get(&self, id: i64) -> Result<Option<Note>> {
        let resp = self
            .authed(self.client.get(self.url(&format!("memory/{id}"))))
            .send()
            .await
            .context("GET /memory/{id}")?;
        if resp.status() == reqwest::StatusCode::NOT_FOUND {
            return Ok(None);
        }
        let note = resp
            .error_for_status()
            .context("server returned error for GET /memory/{id}")?
            .json::<NoteResponse>()
            .await
            .context("parsing get response")?;
        Ok(Some(note.into()))
    }

    async fn count(&self) -> Result<i64> {
        let resp = self
            .authed(self.client.get(self.url("stats")))
            .send()
            .await
            .context("GET /stats")?
            .error_for_status()
            .context("server returned error for GET /stats")?
            .json::<CountResponse>()
            .await
            .context("parsing stats response")?;
        Ok(resp.count)
    }

    async fn archive(&self, id: i64) -> Result<bool> {
        let resp = self
            .authed(self.client.post(self.url(&format!("memory/{id}/archive"))))
            .send()
            .await
            .context("POST /memory/{id}/archive")?
            .error_for_status()
            .context("server returned error for POST /memory/{id}/archive")?
            .json::<BoolResponse>()
            .await
            .context("parsing archive response")?;
        Ok(resp.changed)
    }

    async fn supersede(&self, old_id: i64, new_id: i64) -> Result<bool> {
        let body = SupersedeRequest { new_id };
        let resp = self
            .authed(
                self.client
                    .post(self.url(&format!("memory/{old_id}/supersede"))),
            )
            .json(&body)
            .send()
            .await
            .context("POST /memory/{id}/supersede")?
            .error_for_status()
            .context("server returned error for POST /memory/{id}/supersede")?
            .json::<BoolResponse>()
            .await
            .context("parsing supersede response")?;
        Ok(resp.changed)
    }

    async fn list_by_source_ref(
        &self,
        source_ref_prefix: &str,
        limit: usize,
        include_archived: bool,
        _as_of: Option<i64>,
    ) -> Result<Vec<Note>> {
        let req = self.client.get(self.url("memory")).query(&[
            ("limit", limit.to_string().as_str()),
            ("archived", if include_archived { "true" } else { "false" }),
            ("source_ref", source_ref_prefix),
        ]);
        let resp = self
            .authed(req)
            .send()
            .await
            .context("GET /memory (source_ref filter)")?
            .error_for_status()
            .context("server returned error for GET /memory")?
            .json::<Vec<NoteResponse>>()
            .await
            .context("parsing list response")?;
        Ok(resp.into_iter().map(Into::into).collect())
    }

    async fn harvested_shas(&self) -> Result<HashSet<String>> {
        let resp = self
            .authed(self.client.get(self.url("memory/harvested-shas")))
            .send()
            .await
            .context("GET /memory/harvested-shas")?
            .error_for_status()
            .context("server returned error for GET /memory/harvested-shas")?
            .json::<Vec<String>>()
            .await
            .context("parsing harvested-shas response")?;
        Ok(resp.into_iter().collect())
    }

    async fn has_source_ref(&self, sha: &str) -> Result<bool> {
        // Reuse the list endpoint with the full SHA as prefix; if any results come back,
        // this commit has been harvested.
        let notes = self.list_by_source_ref(sha, 1, true, None).await?;
        Ok(!notes.is_empty())
    }

    /// Remote backend: edge mutations are not supported — no-op.
    async fn add_edge(&self, _from_id: i64, _to_id: i64, _kind: &str) -> Result<()> {
        Ok(())
    }

    /// Remote backend: edge queries are not supported — returns empty lists.
    async fn get_edges(&self, _id: i64) -> Result<(Vec<MemoryEdge>, Vec<MemoryEdge>)> {
        Ok((vec![], vec![]))
    }

    fn backend_kind(&self) -> &'static str {
        "remote"
    }
}

#[cfg(test)]
mod tests;
