#!/usr/bin/env python3
"""Record what each freshly captured wing contains, into MANIFEST.json.

Everything here reads the artifact with plain SQL (or plain git), before any
current-build code has opened it. That ordering is the point: the manifest has
to be an independent record of what the released binary wrote, so that the test
suite comparing it against a post-upgrade read is actually testing something. A
manifest generated by opening the artifact with the current build would agree
with the current build by construction.

Vector tables are vec0 virtual tables, which a plain sqlite3 cannot query, so
row counts come from the `<table>_rowids` shadow table the extension maintains.

Usage: capture_expect.py <wings-dir> <manifest-path> <wing-id|tag|kind>...
"""

import contextlib
import gzip
import hashlib
import json
import os
import re
import shutil
import sqlite3
import subprocess
import sys
import tempfile

SCHEMA = 1


def sha256(path):
    """Digest of the checked-in artifact exactly as it sits on disk."""
    h = hashlib.sha256()
    with open(path, "rb") as fh:
        for block in iter(lambda: fh.read(1 << 20), b""):
            h.update(block)
    return h.hexdigest()


@contextlib.contextmanager
def unpacked(path):
    """Yield a readable path for an artifact, expanding it when it is gzipped."""
    if not path.endswith(".gz"):
        yield path
        return
    tmp = tempfile.mkdtemp()
    try:
        dest = os.path.join(tmp, os.path.basename(path)[: -len(".gz")])
        with gzip.open(path, "rb") as src, open(dest, "wb") as out:
            shutil.copyfileobj(src, out)
        yield dest
    finally:
        shutil.rmtree(tmp, ignore_errors=True)


def connect(path):
    return sqlite3.connect(f"file:{path}?mode=ro", uri=True)


def scalar(conn, sql, default=0):
    try:
        row = conn.execute(sql).fetchone()
    except sqlite3.Error:
        return default
    return row[0] if row and row[0] is not None else default


def table_sql(conn, name):
    row = conn.execute(
        "SELECT sql FROM sqlite_master WHERE type='table' AND name=?", (name,)
    ).fetchone()
    return row[0] if row else ""


def index_expect(path):
    conn = connect(path)
    declared = table_sql(conn, "embeddings")
    storage = "float768" if "FLOAT[768]" in declared else "int8"

    # A term that is in the source and therefore must survive into the FTS
    # index. Picked from the stored chunk text, never hardcoded, so the check
    # keeps working if the sample repo is rewritten.
    row = conn.execute(
        "SELECT f.path, c.content FROM chunks c JOIN files f ON c.file_id = f.id "
        "ORDER BY c.id LIMIT 1"
    ).fetchone()
    fts_query, fts_path = "", ""
    if row:
        fts_path = row[0]
        words = re.findall(r"[A-Za-z_]{6,}", row[1] or "")
        if words:
            fts_query = words[0]

    expect = {
        "file_count": scalar(conn, "SELECT count(*) FROM files"),
        "chunk_count": scalar(conn, "SELECT count(*) FROM chunks"),
        "embedding_count": scalar(conn, "SELECT count(*) FROM embeddings_rowids"),
        # The code graph is a whole subsystem the row counts above say nothing
        # about: a migration can leave files and chunks untouched and still
        # empty graph_edges.
        "graph_edge_count": scalar(conn, "SELECT count(*) FROM graph_edges"),
        "vector_storage": storage,
        "fts_query": fts_query,
        "fts_expect_path": fts_path,
    }
    conn.close()
    return expect


def memory_expect(path):
    conn = connect(path)
    notes = conn.execute(
        "SELECT id, title, status, superseded_by FROM notes ORDER BY id"
    ).fetchall()
    by_id = {n[0]: n for n in notes}

    chain = next((n for n in notes if n[3] is not None), None)
    successor = by_id.get(chain[3]) if chain else None
    # `memory supersede` archives its loser, so an archived entry picked at
    # random could be the same row as the superseded one and the two assertions
    # would collapse into one. Prefer an entry archived on its own.
    archived = next(
        (n for n in notes if n[2] == "archived" and n[3] is None),
        next((n for n in notes if n[2] == "archived"), None),
    )

    # Memory full-text search only returns active entries, so the term has to
    # come from one. The obvious first-by-id note is the superseded one, which
    # `memory supersede` archived, and a query for its text is meant to return
    # nothing.
    body = conn.execute(
        "SELECT body FROM notes WHERE body != '' AND status = 'active' "
        "ORDER BY id LIMIT 1"
    ).fetchone()
    fts_query = ""
    if body:
        words = re.findall(r"[A-Za-z]{6,}", body[0])
        if words:
            fts_query = words[0]

    columns = [r[1] for r in conn.execute("PRAGMA table_info(notes)").fetchall()]

    expect = {
        "note_count": len(notes),
        "active_note_count": sum(1 for n in notes if n[2] == "active"),
        "archived_title": archived[1] if archived else "",
        "superseded_title": chain[1] if chain else "",
        "successor_title": successor[1] if successor else "",
        "memory_fts_query": fts_query,
        # Recorded so the suite can prove a pre-ADR-068 wing really is one
        # before it asserts the backfill filled it in. Without this an
        # accidentally pre-migrated fixture would make the backfill assertion
        # pass without the backfill ever running.
        "entity_id_present": "entity_id" in columns,
        "note_vector_count": scalar(
            conn, "SELECT count(*) FROM note_embeddings_rowids"
        ),
    }
    conn.close()
    return expect


def registry_expect(path):
    conn = connect(path)
    expect = {
        "project_count": scalar(conn, "SELECT count(*) FROM projects"),
        "dep_count": scalar(conn, "SELECT count(*) FROM project_deps"),
    }
    conn.close()
    return expect


def git_notes_expect(path):
    """Read the note titles straight off the bundle with git, never with spelunk."""
    with tempfile.TemporaryDirectory() as tmp:
        repo = os.path.join(tmp, "repo")
        subprocess.run(
            ["git", "clone", "--quiet", path, repo], check=True, capture_output=True
        )
        subprocess.run(
            [
                "git",
                "-C",
                repo,
                "fetch",
                "--quiet",
                "origin",
                "refs/notes/spelunk:refs/notes/spelunk",
            ],
            check=True,
            capture_output=True,
        )
        listing = subprocess.run(
            ["git", "-C", repo, "notes", "--ref=spelunk", "list"],
            check=True,
            capture_output=True,
            text=True,
        ).stdout
        # Keyed by the record id the writing binary assigned, not by title.
        # A released binary really does repeat a line in its log (0.9.3 writes
        # each entry twice), so the number of distinct entries a reader owes
        # the caller is the number of distinct ids, and recording that is what
        # lets the suite catch a reader that hands duplicates back.
        entries = {}
        for line in listing.splitlines():
            blob = line.split()[0]
            body = subprocess.run(
                ["git", "-C", repo, "cat-file", "blob", blob],
                check=True,
                capture_output=True,
                text=True,
            ).stdout
            for note_line in body.splitlines():
                note_line = note_line.strip()
                if not note_line.startswith("{"):
                    continue
                try:
                    record = json.loads(note_line)
                except json.JSONDecodeError:
                    continue
                title = record.get("title")
                if not title:
                    continue
                entries.setdefault(
                    record.get("id", title),
                    {
                        "title": title,
                        "kind": record.get("kind", ""),
                        "body": record.get("body", ""),
                    },
                )
    # Sorted by str: a record missing an id falls back to its title as the key,
    # and sorting ints against strs is a TypeError.
    return {"era_entries": [entries[k] for k in sorted(entries, key=str)]}


ARTIFACTS = {
    "index": ("index.db.gz", index_expect),
    "memory": ("memory.db.gz", memory_expect),
    "registry": ("registry.db.gz", registry_expect),
    "git-notes": ("notes.bundle", git_notes_expect),
}


def main():
    wings_dir, manifest_path = sys.argv[1], sys.argv[2]
    built = sys.argv[3:]

    existing = {}
    if os.path.exists(manifest_path):
        with open(manifest_path) as fh:
            for wing in json.load(fh).get("wings", []):
                existing[wing["id"]] = wing

    for entry in built:
        wing_id, tag, kind = entry.split("|")
        artifact, reader = ARTIFACTS[kind]
        path = os.path.join(wings_dir, wing_id, artifact)
        with unpacked(path) as readable:
            expect = reader(readable)
        existing[wing_id] = {
            "id": wing_id,
            "producer": tag.lstrip("v"),
            "kind": kind,
            "artifact": artifact,
            # checksums.txt pins the release binaries, which says nothing about
            # the artifacts. This pins the artifacts, so a wing that changes
            # without its expectations being recaptured is a test failure
            # rather than something a reviewer has to notice in a binary diff.
            "sha256": sha256(path),
            "expect": expect,
        }

    manifest = {
        "schema": SCHEMA,
        "wings": [existing[k] for k in sorted(existing)],
    }
    with open(manifest_path, "w") as fh:
        json.dump(manifest, fh, indent=2, sort_keys=True)
        fh.write("\n")
    print(f"wrote {manifest_path} with {len(manifest['wings'])} wings")


if __name__ == "__main__":
    main()
